In [1]:
import gym

env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

[2017-06-29 23:31:27,133] Making new env: CartPole-v0
[2017-06-29 23:31:27,526] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [2]:
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-06-29 22:14:08,627] Making new env: CartPole-v0


[ 0.01366236  0.02554962 -0.02188913  0.02358918]
[ 0.01417335  0.22097853 -0.02141735 -0.27591885]
[ 0.01859293  0.02616859 -0.02693573  0.00993282]
[ 0.0191163   0.22166628 -0.02673707 -0.29112547]
[ 0.02354962  0.02693556 -0.03255958 -0.00699357]
[ 0.02408833 -0.16770467 -0.03269945  0.27524122]
[ 0.02073424 -0.3623452  -0.02719463  0.557434  ]
[ 0.01348734 -0.16685225 -0.01604595  0.25630876]
[ 0.01015029 -0.36174147 -0.01091977  0.54388766]
[  2.91546232e-03  -1.66467782e-01  -4.20185754e-05   2.47784244e-01]
[-0.00041389  0.02865477  0.00491367 -0.04491194]
[  1.59202090e-04  -1.66537295e-01   4.01542758e-03   2.49317238e-01]
[-0.00317154 -0.36171636  0.00900177  0.54326401]
[-0.01040587 -0.55696365  0.01986705  0.83876957]
[-0.02154514 -0.36211854  0.03664244  0.5524001 ]
[-0.02878751 -0.55773541  0.04769045  0.85639891]
[-0.03994222 -0.3632946   0.06481842  0.57908498]
[-0.04720811 -0.16913805  0.07640012  0.30750502]
[-0.05059088  0.02481684  0.08255022  0.03986115]
[-0.050094

In [3]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)

[2017-06-29 22:14:24,398] Making new env: CartPole-v0


Discrete(2)
Box(4,)


In [6]:
print(env.observation_space.high)
#> array([ 2.4       ,         inf,  0.20943951,         inf])
print(env.observation_space.low)
#> array([-2.4       ,        -inf, -0.20943951,        -inf])

[  4.80000000e+00   3.40282347e+38   4.18879020e-01   3.40282347e+38]
[ -4.80000000e+00  -3.40282347e+38  -4.18879020e-01  -3.40282347e+38]


In [7]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [8]:
from gym import envs
print(envs.registry.all())

dict_values([EnvSpec(Enduro-ram-v0), EnvSpec(Gravitar-v0), EnvSpec(PitfallNoFrameskip-v4), EnvSpec(PitfallDeterministic-v0), EnvSpec(Breakout-ram-v0), EnvSpec(Berzerk-v4), EnvSpec(Krull-ram-v0), EnvSpec(Hero-ram-v4), EnvSpec(TimePilot-ram-v0), EnvSpec(Pong-ramDeterministic-v4), EnvSpec(HalfCheetah-v1), EnvSpec(Jamesbond-v4), EnvSpec(Breakout-v0), EnvSpec(UpNDown-v4), EnvSpec(DemonAttackNoFrameskip-v4), EnvSpec(Frostbite-ramDeterministic-v4), EnvSpec(YarsRevenge-v4), EnvSpec(AsterixNoFrameskip-v4), EnvSpec(SeaquestNoFrameskip-v0), EnvSpec(BankHeistNoFrameskip-v0), EnvSpec(Alien-ramDeterministic-v0), EnvSpec(EnduroDeterministic-v4), EnvSpec(Pendulum-v0), EnvSpec(YarsRevenge-ramDeterministic-v0), EnvSpec(DoubleDunk-ramDeterministic-v0), EnvSpec(PhoenixNoFrameskip-v4), EnvSpec(TennisNoFrameskip-v0), EnvSpec(PrivateEyeNoFrameskip-v0), EnvSpec(Asteroids-ramNoFrameskip-v0), EnvSpec(Hero-ramDeterministic-v0), EnvSpec(BeamRider-v4), EnvSpec(BipedalWalkerHardcore-v2), EnvSpec(SpaceInvaders-v0), 

In [9]:
import gym
from gym import wrappers
env = gym.make('CartPole-v0')
env = wrappers.Monitor(env, '/tmp/cartpole-experiment-1')
for i_episode in range(100):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break

[2017-06-29 22:14:48,631] Making new env: CartPole-v0
[2017-06-29 22:14:48,633] Creating monitor directory /tmp/cartpole-experiment-1
[2017-06-29 22:14:48,660] Starting new video recorder writing to C:\tmp\cartpole-experiment-1\openaigym.video.0.8180.video000000.mp4


[ 0.0097895  -0.03798243 -0.02378331  0.02808844]
[ 0.00902985 -0.23275538 -0.02322154  0.3131736 ]
[ 0.00437475 -0.42753896 -0.01695807  0.59844368]
[-0.00417603 -0.23218389 -0.0049892   0.30046777]
[-0.00881971 -0.42723437  0.00102016  0.59157303]
[-0.0173644  -0.23212672  0.01285162  0.29921163]
[-0.02200693 -0.03719029  0.01883585  0.01060941]
[-0.02275074 -0.23257724  0.01904804  0.30917525]
[-0.02740228 -0.42796533  0.02523154  0.60780402]
[-0.03596159 -0.62343079  0.03738763  0.90832617]
[-0.04843021 -0.81903835  0.05555415  1.21252186]
[-0.06481097 -0.62467569  0.07980459  0.93775217]
[-0.07730449 -0.82077772  0.09855963  1.25440666]
[-0.09372004 -0.62704632  0.12364776  0.99414949]

[2017-06-29 22:14:49,698] Starting new video recorder writing to C:\tmp\cartpole-experiment-1\openaigym.video.0.8180.video000001.mp4



[-0.10626097 -0.82358587  0.14353075  1.32296793]
[-0.12273268 -1.02019952  0.16999011  1.65690908]
[-0.14313667 -0.82741937  0.20312829  1.42164358]
Episode finished after 17 timesteps
[-0.03399474 -0.01547672 -0.03142496  0.03243667]
[-0.03430428  0.18008145 -0.03077623 -0.26999319]
[-0.03070265 -0.0145881  -0.03617609  0.01282608]
[-0.03099441 -0.20917307 -0.03591957  0.29387911]
[-0.03517787 -0.0135579  -0.03004199 -0.00991245]
[-0.03544903  0.18198172 -0.03024024 -0.31192055]
[-0.0318094   0.37752115 -0.03647865 -0.61398487]
[-0.02425897  0.57313334 -0.04875835 -0.9179303 ]
[-0.01279631  0.76887936 -0.06711695 -1.22552965]
[ 0.00258128  0.96479823 -0.09162755 -1.53846386]
[ 0.02187724  1.1608955  -0.12239682 -1.85827668]
[ 0.04509515  0.96731124 -0.15956236 -1.60596752]
[ 0.06444138  1.16391994 -0.19168171 -1.94384679]
Episode finished after 13 timesteps
[-0.01711134  0.04964841  0.03167523 -0.04729465]
[-0.01611837 -0.14591308  0.03072934  0.25521141]
[-0.01903663  0.04875695  0

[2017-06-29 22:14:52,384] Starting new video recorder writing to C:\tmp\cartpole-experiment-1\openaigym.video.0.8180.video000008.mp4


[ 0.1974744   1.21181518 -0.20167615 -1.97277507]
Episode finished after 33 timesteps
[-0.02530506  0.03412582 -0.01390357 -0.00098288]
[-0.02462255  0.22944438 -0.01392323 -0.29801992]
[-0.02003366  0.03452364 -0.01988363 -0.00976045]
[-0.01934319 -0.16030759 -0.02007884  0.27658323]
[-0.02254934 -0.35513741 -0.01454717  0.56286627]
[-0.02965209 -0.15981438 -0.00328985  0.265636  ]
[-0.03284837 -0.35488922  0.00202287  0.55727947]
[-0.03994616 -0.55003952  0.01316846  0.85059903]
[-0.05094695 -0.74533853  0.03018044  1.14739357]
[-0.06585372 -0.94084126  0.05312831  1.44938583]
[-0.08467054 -0.7464111   0.08211603  1.17376446]
[-0.09959877 -0.55244676  0.10559132  0.90791333]
[-0.1106477  -0.74882744  0.12374959  1.2318299 ]
[-0.12562425 -0.55549498  0.14838618  0.98033848]
[-0.13673415 -0.36263982  0.16799295  0.7377003 ]
[-0.14398695 -0.17018697  0.18274696  0.5022429 ]
[-0.14739069  0.02195249  0.19279182  0.27226197]
[-0.14695164  0.21387585  0.19823706  0.04604085]
[-0.14267412  

[2017-06-29 22:15:01,563] Starting new video recorder writing to C:\tmp\cartpole-experiment-1\openaigym.video.0.8180.video000027.mp4


[ 0.06631     0.39335436  0.1593071   0.35916166]
[ 0.07417709  0.5858955   0.16649034  0.12064547]
[ 0.085895    0.77828935  0.16890325 -0.11523246]
[ 0.10146078  0.97063925  0.1665986  -0.35022974]
[ 0.12087357  0.77358833  0.159594   -0.00999204]
[ 0.13634534  0.57658031  0.15939416  0.32848632]
[ 0.14787694  0.37959075  0.16596389  0.66688867]
[ 0.15546876  0.18259718  0.17930166  1.00688857]
[ 0.1591207  -0.01440658  0.19943943  1.3500895 ]
Episode finished after 35 timesteps
[-0.00041043  0.04363174 -0.0139763   0.04637641]
[ 0.00046221  0.23895129 -0.01304877 -0.2506832 ]
[ 0.00524123  0.04401808 -0.01806244  0.03785549]
[ 0.0061216  -0.15084026 -0.01730533  0.32478525]
[ 0.00310479 -0.34571159 -0.01080962  0.61196096]
[-0.00380944 -0.15044024  0.0014296   0.31589309]
[-0.00681825 -0.34558253  0.00774746  0.60902652]
[-0.0137299  -0.15056973  0.01992799  0.31879384]
[-0.01674129 -0.34596975  0.02630386  0.61769411]
[-0.02366069 -0.54144908  0.03865775  0.91854412]
[-0.03448967 -

[2017-06-29 22:15:15,339] Starting new video recorder writing to C:\tmp\cartpole-experiment-1\openaigym.video.0.8180.video000064.mp4


[ 0.11076196  0.96646788 -0.10002344 -1.34739685]
[ 0.13009132  0.77273535 -0.12697137 -1.08760839]
[ 0.14554603  0.969282   -0.14872354 -1.41728442]
[ 0.16493167  1.1658993  -0.17706923 -1.75251839]
Episode finished after 23 timesteps
[-0.02380439  0.02238727 -0.04338203 -0.03635955]
[-0.02335665 -0.17208659 -0.04410922  0.24232647]
[-0.02679838  0.02363676 -0.03926269 -0.0639369 ]
[-0.02632564 -0.17090091 -0.04054143  0.21610445]
[-0.02974366 -0.36542054 -0.03621934  0.49572822]
[-0.03705207 -0.16980706 -0.02630478  0.19185428]
[-0.04044821 -0.36454302 -0.02246769  0.47612446]
[-0.04773908 -0.55934064 -0.0129452   0.76164219]
[-0.05892589 -0.75428189  0.00228764  1.05022379]
[-0.07401153 -0.94943412  0.02329212  1.34362392]
[-0.09300021 -1.14484121  0.0501646   1.64350232]
[-0.11589703 -1.34051325  0.08303464  1.95138336]
[-0.1427073  -1.14636627  0.12206231  1.68555041]
[-0.16563462 -0.95284997  0.15577332  1.43323297]
[-0.18469162 -0.75995488  0.18443798  1.19300611]
[-0.19989072 -

In [2]:
import gym
env.close()

In [12]:
import gym
gym.upload('/tmp/cartpole-experiment-1', api_key='DELETED KEY')

[2017-06-29 22:15:46,554] [CartPole-v0] Uploading 100 episodes of training data
[2017-06-29 22:15:49,160] [CartPole-v0] Uploading videos of 5 training episodes (12683 bytes)
[2017-06-29 22:15:49,655] [CartPole-v0] Creating evaluation object from /tmp/cartpole-experiment-1 with learning curve and training video
[2017-06-29 22:15:50,147] 
****************************************************
You successfully uploaded your evaluation on CartPole-v0 to
OpenAI Gym! You can find it at:

    https://gym.openai.com/evaluations/eval_fdleahYxQFGjwydLu4sK5Q

****************************************************


In [3]:
## FROM SENTDEX YOUTUBE

import gym
import random
import numpy as np
from statistics import mean, median
from collections import Counter 

LR = 1e-3
goal_steps = 500
score_requirements = 50
initial_games = 10000

env = gym.make('CartPole-v0')
env.reset()

def some_random_games_first():
    for episode in range(5):
        env.reset()
        for t in range(goal_steps):
            env.render()
            action = env.action_space.sample()
            observation, reward, done, info = env.step(action)
            if done:
                break
                
##some_random_games_first()

[2017-06-29 23:32:02,407] Making new env: CartPole-v0


In [36]:
def initial_population():
    training_data = []
    scores = []
    accepted_scores = []
    
    for _ in range(initial_games):
        score = 0
        game_memory = []
        prev_observations = []
        for _ in range(goal_steps):
            action = random.randrange(0, 2)
            observation, reward, done, info = env.step(action)
            
            if len(prev_observations) > 0:
                game_memory.append([prev_observations, action])
                
            prev_observation = observation
            score += reward 
            if done:
                break
                
        if score >= score_requirements:
            accepted_scores.append(score)
            for data in game_memory:
                if data[1] == 1:
                    output = [0, 1]
                elif data[1] == 0:
                    output = [1,0]
                training_data.append([data[0], output])
        env.reset()
        scores.append(score)
        
    training_data_save = np.array(training_data)
    np.save('saved.npy', training_data_save)
    
    print('Average accepted score:', mean(accepted_scores))
    print('Median accepted score:', median(accepted_scores))
    # Hard coded for now
    print(len(Counter(accepted_scores)))
    
    return training_data

In [37]:
initial_population()

Average accepted score: 61.31720430107527
Median accepted score: 57.0
49


[]

## Create the NN

In [7]:
import tensorflow as tf

In [12]:
def neural_network_model(input_size):
    network = input_data(shape=[None, input_size, 1], name = 'input')
    
    # 128 node, rectify linear
    network = fully_connected(network, 128, activation = 'relu')
    network = dropout(network, 0.8)
    
    network = fully_connected(network, 256, activation = 'relu')
    network = dropout(network, 0.8)
    
    network = fully_connected(network, 512, activation = 'relu')
    network = dropout(network, 0.8)
    
    network = fully_connected(network, 256, activation = 'relu')
    network = dropout(network, 0.8)
    
    network = fully_connected(network, 128, activation = 'relu')
    network = dropout(network, 0.8)
    
    network = fully_connected(netwok, 2, activation='softmax')
    network = regression(network, optimizer='adam', learning_rate = LR,
                                   loss='categorical_crossentropy', name='targets')
    model = tflearn.DNNregression(network, tensorboard_dir='log')
    
    return model


In [33]:
training_data = initial_population()
model = train_model(training_data)

Average accepted score: 62.10236220472441
Median accepted score: 58.0
Counter({52.0: 30, 51.0: 26, 56.0: 24, 53.0: 22, 50.0: 20, 54.0: 20, 55.0: 18, 60.0: 18, 62.0: 18, 58.0: 17, 57.0: 14, 61.0: 14, 63.0: 12, 65.0: 12, 59.0: 11, 64.0: 10, 67.0: 7, 68.0: 7, 77.0: 7, 74.0: 6, 66.0: 5, 72.0: 5, 76.0: 5, 78.0: 4, 84.0: 4, 96.0: 4, 69.0: 3, 71.0: 3, 73.0: 3, 80.0: 3, 81.0: 3, 85.0: 3, 94.0: 3, 70.0: 2, 79.0: 2, 90.0: 2, 93.0: 2, 75.0: 1, 83.0: 1, 86.0: 1, 89.0: 1, 97.0: 1, 102.0: 1, 104.0: 1, 105.0: 1, 106.0: 1, 110.0: 1, 112.0: 1, 114.0: 1})


IndexError: list index out of range

In [35]:
list(map())

AttributeError: 'list' object has no attribute 'keys'

In [46]:
X = np.array([i[0] for i in training_data])
X.reshape(-1, 49, 1)
y = [i[1] for i in training_data]

print(X)
#model = neural_network_model(input_size = len(X[0]))


[]


In [42]:
 model = neural_network_model(input_size = len(X[0]))
    
model.fit({'input':X}, {'targets':y}, n_epoch=5, snapshot_step = 500, show_metric=True,
          run_id='openaistuff')
#return model



In [43]:
train_model(initial_population())

Average accepted score: 60.27913279132791
Median accepted score: 58.0
38


NameError: name 'input_data' is not defined

In [50]:
np.array([i[0] for i in training_data]).reshape(-1, len(training_data[0][0]), 1)

IndexError: list index out of range